module.exports = async function (app) {
  return new Promise((resolve, reject) => {
    var Constants = {
      token: {
        address: {
          mainnet: "0xdf49c9f599a0a9049d97cff34d0c30e468987389",
          testnet: "0x2beF0d7531f0aaE08ADc26A0442Ba8D0516590d0",
          tetherMainnet: "0xdac17f958d2ee523a2206206994597c13d831ec7",
          tetherTesnet: "0x3B2243E3Aeb6d4A102061BCE6C5c233c2C08fF65",
          daiMainnet: "0x6b175474e89094c44da98b954eedeac495271d0f",
          daiTesnet: "0x7d6550Bb3946c0BB0701c75baBE2f679E01F3f3E",
        },

        abi: [
          {
            constant: true,
            inputs: [],
            name: "name",
            outputs: [{ name: "", type: "string" }],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { name: "_spender", type: "address" },
              { name: "_value", type: "uint256" },
            ],
            name: "approve",
            outputs: [{ name: "success", type: "bool" }],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: true,
            inputs: [],
            name: "totalSupply",
            outputs: [{ name: "", type: "uint256" }],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { name: "_from", type: "address" },
              { name: "_to", type: "address" },
              { name: "_value", type: "uint256" },
            ],
            name: "transferFrom",
            outputs: [{ name: "success", type: "bool" }],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: true,
            inputs: [],
            name: "decimals",
            outputs: [{ name: "", type: "uint8" }],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: false,
            inputs: [],
            name: "withdraw",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: true,
            inputs: [{ name: "", type: "address" }],
            name: "balanceOf",
            outputs: [{ name: "", type: "uint256" }],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: true,
            inputs: [],
            name: "owner",
            outputs: [{ name: "", type: "address" }],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: true,
            inputs: [],
            name: "symbol",
            outputs: [{ name: "", type: "string" }],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { name: "to", type: "address" },
              { name: "value", type: "uint256" },
            ],
            name: "transfer",
            outputs: [{ name: "success", type: "bool" }],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { name: "to", type: "address" },
              { name: "value", type: "uint256" },
              { name: "data", type: "bytes" },
            ],
            name: "transfer",
            outputs: [{ name: "success", type: "bool" }],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: true,
            inputs: [
              { name: "_from", type: "address" },
              { name: "_value", type: "uint256" },
              { name: "_data", type: "bytes" },
            ],
            name: "tokenFallback",
            outputs: [],
            payable: false,
            stateMutability: "pure",
            type: "function",
          },
          {
            constant: true,
            inputs: [
              { name: "", type: "address" },
              { name: "", type: "address" },
            ],
            name: "allowance",
            outputs: [{ name: "", type: "uint256" }],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: false,
            inputs: [{ name: "newOwner", type: "address" }],
            name: "transferOwnership",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { name: "token", type: "address" },
              { name: "to", type: "address" },
              { name: "val", type: "uint256" },
            ],
            name: "transferToken",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "constructor",
          },
          { payable: true, stateMutability: "payable", type: "fallback" },
          {
            anonymous: false,
            inputs: [
              { indexed: true, name: "from", type: "address" },
              { indexed: true, name: "to", type: "address" },
              { indexed: false, name: "value", type: "uint256" },
            ],
            name: "Transfer",
            type: "event",
          },
          {
            anonymous: false,
            inputs: [
              { indexed: true, name: "tokenOwner", type: "address" },
              { indexed: true, name: "spender", type: "address" },
              { indexed: false, name: "tokens", type: "uint256" },
            ],
            name: "Approval",
            type: "event",
          },
        ],
      },
      campaign: {
        address: {
          mainnet: "",
          testnet: "0x28D37ED4c039B65d8e999eDE2956CeC4e88a70df",
          mainnetBep20: "",
          testnetBep20: "0x98255Fc154A38a32daa2c26060e219e8DBF024bc",
        },
        abi: [
          {
            anonymous: false,
            inputs: [
              {
                indexed: true,
                internalType: "bytes32",
                name: "id",
                type: "bytes32",
              },
              {
                indexed: true,
                internalType: "bytes32",
                name: "prom",
                type: "bytes32",
              },
            ],
            name: "CampaignApplied",
            type: "event",
          },
          {
            anonymous: false,
            inputs: [
              {
                indexed: true,
                internalType: "bytes32",
                name: "id",
                type: "bytes32",
              },
              {
                indexed: false,
                internalType: "uint64",
                name: "startDate",
                type: "uint64",
              },
              {
                indexed: false,
                internalType: "uint64",
                name: "endDate",
                type: "uint64",
              },
              {
                indexed: false,
                internalType: "string",
                name: "dataUrl",
                type: "string",
              },
            ],
            name: "CampaignCreated",
            type: "event",
          },
          {
            anonymous: false,
            inputs: [
              {
                indexed: true,
                internalType: "bytes32",
                name: "id",
                type: "bytes32",
              },
              {
                indexed: false,
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            name: "CampaignFunded",
            type: "event",
          },
          {
            anonymous: false,
            inputs: [
              {
                indexed: true,
                internalType: "bytes32",
                name: "id",
                type: "bytes32",
              },
            ],
            name: "CampaignFundsSpent",
            type: "event",
          },
          {
            anonymous: false,
            inputs: [
              {
                indexed: true,
                internalType: "bytes32",
                name: "id",
                type: "bytes32",
              },
            ],
            name: "PromAccepted",
            type: "event",
          },
          {
            anonymous: false,
            inputs: [
              {
                indexed: true,
                internalType: "bytes32",
                name: "id",
                type: "bytes32",
              },
              {
                indexed: false,
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
            ],
            name: "PromPayed",
            type: "event",
          },
          { stateMutability: "payable", type: "fallback" },
          {
            inputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
              { internalType: "uint8", name: "typeSN", type: "uint8" },
              { internalType: "string", name: "idPost", type: "string" },
              { internalType: "string", name: "idUser", type: "string" },
            ],
            name: "applyCampaign",
            outputs: [
              { internalType: "bytes32", name: "idProm", type: "bytes32" },
            ],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "uint8", name: "typeSN", type: "uint8" },
              { internalType: "string", name: "idPost", type: "string" },
              { internalType: "string", name: "idUser", type: "string" },
              { internalType: "bytes32", name: "idRequest", type: "bytes32" },
            ],
            name: "ask",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "uint8", name: "typeSN", type: "uint8" },
              { internalType: "string", name: "idPost", type: "string" },
              { internalType: "string", name: "idUser", type: "string" },
              { internalType: "bytes32", name: "idProm", type: "bytes32" },
            ],
            name: "askBounty",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
            name: "campaigns",
            outputs: [
              { internalType: "address", name: "advertiser", type: "address" },
              { internalType: "string", name: "dataUrl", type: "string" },
              { internalType: "uint64", name: "startDate", type: "uint64" },
              { internalType: "uint64", name: "endDate", type: "uint64" },
              { internalType: "uint64", name: "nbProms", type: "uint64" },
              { internalType: "uint64", name: "nbValidProms", type: "uint64" },
              {
                components: [
                  { internalType: "address", name: "token", type: "address" },
                  { internalType: "uint256", name: "amount", type: "uint256" },
                ],
                internalType: "struct campaign.Fund",
                name: "funds",
                type: "tuple",
              },
            ],
            stateMutability: "view",
            type: "function",
          },
          {
            inputs: [
              { internalType: "string", name: "dataUrl", type: "string" },
              { internalType: "uint64", name: "startDate", type: "uint64" },
              { internalType: "uint64", name: "endDate", type: "uint64" },
            ],
            name: "createCampaign",
            outputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
            ],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "string", name: "dataUrl", type: "string" },
              { internalType: "uint64", name: "startDate", type: "uint64" },
              { internalType: "uint64", name: "endDate", type: "uint64" },
              { internalType: "uint256[]", name: "ratios", type: "uint256[]" },
              { internalType: "address", name: "token", type: "address" },
              { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            name: "createPriceFundAll",
            outputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
            ],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "string", name: "dataUrl", type: "string" },
              { internalType: "uint64", name: "startDate", type: "uint64" },
              { internalType: "uint64", name: "endDate", type: "uint64" },
              {
                internalType: "uint256[]",
                name: "bounties",
                type: "uint256[]",
              },
              { internalType: "address", name: "token", type: "address" },
              { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            name: "createPriceFundBounty",
            outputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
            ],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "string", name: "dataUrl", type: "string" },
              { internalType: "uint64", name: "startDate", type: "uint64" },
              { internalType: "uint64", name: "endDate", type: "uint64" },
              { internalType: "uint256", name: "likeRatio", type: "uint256" },
              { internalType: "uint256", name: "viewRatio", type: "uint256" },
              { internalType: "address", name: "token", type: "address" },
              { internalType: "uint256", name: "amount", type: "uint256" },
              { internalType: "uint256", name: "limit", type: "uint256" },
            ],
            name: "createPriceFundYt",
            outputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
            ],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
            ],
            name: "endCampaign",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
              { internalType: "address", name: "token", type: "address" },
              { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            name: "fundCampaign",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
            ],
            name: "getBounties",
            outputs: [
              { internalType: "uint256[]", name: "bounty", type: "uint256[]" },
            ],
            stateMutability: "view",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idProm", type: "bytes32" },
            ],
            name: "getGains",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
              { internalType: "uint8", name: "typeSN", type: "uint8" },
              { internalType: "string", name: "idPost", type: "string" },
              { internalType: "string", name: "idUser", type: "string" },
            ],
            name: "getIsUsed",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            stateMutability: "view",
            type: "function",
          },
          {
            inputs: [],
            name: "getOracleFee",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
            ],
            name: "getProms",
            outputs: [
              { internalType: "bytes32[]", name: "cproms", type: "bytes32[]" },
            ],
            stateMutability: "view",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
            ],
            name: "getRatios",
            outputs: [
              { internalType: "uint8[]", name: "types", type: "uint8[]" },
              {
                internalType: "uint256[]",
                name: "likeRatios",
                type: "uint256[]",
              },
              {
                internalType: "uint256[]",
                name: "shareRatios",
                type: "uint256[]",
              },
              {
                internalType: "uint256[]",
                name: "viewRatios",
                type: "uint256[]",
              },
              { internalType: "uint256[]", name: "limits", type: "uint256[]" },
            ],
            stateMutability: "view",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
            ],
            name: "getRemainingFunds",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idProm", type: "bytes32" },
            ],
            name: "getResults",
            outputs: [
              { internalType: "bytes32[]", name: "creq", type: "bytes32[]" },
            ],
            stateMutability: "view",
            type: "function",
          },
          {
            inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
            name: "isAlreadyUsed",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            stateMutability: "view",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
              { internalType: "string", name: "dataUrl", type: "string" },
              { internalType: "uint64", name: "startDate", type: "uint64" },
              { internalType: "uint64", name: "endDate", type: "uint64" },
            ],
            name: "modCampaign",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "address", name: "token", type: "address" },
              { internalType: "bool", name: "accepted", type: "bool" },
            ],
            name: "modToken",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [{ internalType: "address", name: "", type: "address" }],
            name: "oraclelist",
            outputs: [
              { internalType: "address", name: "advertiser", type: "address" },
              {
                components: [
                  { internalType: "address", name: "token", type: "address" },
                  { internalType: "uint256", name: "amount", type: "uint256" },
                ],
                internalType: "struct campaign.Fund",
                name: "funds",
                type: "tuple",
              },
            ],
            stateMutability: "view",
            type: "function",
          },
          {
            inputs: [],
            name: "owner",
            outputs: [
              { internalType: "address payable", name: "", type: "address" },
            ],
            stateMutability: "view",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
              { internalType: "uint8", name: "typeSN", type: "uint8" },
              { internalType: "uint256", name: "likeRatio", type: "uint256" },
              { internalType: "uint256", name: "shareRatio", type: "uint256" },
              { internalType: "uint256", name: "viewRatio", type: "uint256" },
              { internalType: "uint256", name: "limit", type: "uint256" },
            ],
            name: "priceRatioCampaign",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
            name: "proms",
            outputs: [
              { internalType: "address", name: "influencer", type: "address" },
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
              { internalType: "bool", name: "isAccepted", type: "bool" },
              { internalType: "bool", name: "isPayed", type: "bool" },
              {
                components: [
                  { internalType: "address", name: "token", type: "address" },
                  { internalType: "uint256", name: "amount", type: "uint256" },
                ],
                internalType: "struct campaign.Fund",
                name: "funds",
                type: "tuple",
              },
              { internalType: "uint8", name: "typeSN", type: "uint8" },
              { internalType: "string", name: "idPost", type: "string" },
              { internalType: "string", name: "idUser", type: "string" },
              { internalType: "uint64", name: "nbResults", type: "uint64" },
              { internalType: "bytes32", name: "prevResult", type: "bytes32" },
            ],
            stateMutability: "view",
            type: "function",
          },
          {
            inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
            name: "results",
            outputs: [
              { internalType: "bytes32", name: "idProm", type: "bytes32" },
              { internalType: "uint64", name: "likes", type: "uint64" },
              { internalType: "uint64", name: "shares", type: "uint64" },
              { internalType: "uint64", name: "views", type: "uint64" },
            ],
            stateMutability: "view",
            type: "function",
          },
          {
            inputs: [{ internalType: "address", name: "a", type: "address" }],
            name: "setOracle",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
            ],
            name: "startCampaign",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "address", name: "_from", type: "address" },
              { internalType: "uint256", name: "_value", type: "uint256" },
              { internalType: "bytes", name: "_data", type: "bytes" },
            ],
            name: "tokenFallback",
            outputs: [
              { internalType: "bytes32", name: "hash", type: "bytes32" },
            ],
            stateMutability: "pure",
            type: "function",
          },
          {
            inputs: [
              {
                internalType: "address payable",
                name: "newOwner",
                type: "address",
              },
            ],
            name: "transferOwnership",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "address", name: "token", type: "address" },
              { internalType: "address", name: "to", type: "address" },
              { internalType: "uint256", name: "val", type: "uint256" },
            ],
            name: "transferToken",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idRequest", type: "bytes32" },
              { internalType: "uint64", name: "likes", type: "uint64" },
              { internalType: "uint64", name: "shares", type: "uint64" },
              { internalType: "uint64", name: "views", type: "uint64" },
            ],
            name: "update",
            outputs: [{ internalType: "bool", name: "ok", type: "bool" }],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idProm", type: "bytes32" },
            ],
            name: "updateBounty",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idProm", type: "bytes32" },
              { internalType: "uint256", name: "nbAbos", type: "uint256" },
            ],
            name: "updateBounty",
            outputs: [{ internalType: "bool", name: "ok", type: "bool" }],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idCampaign", type: "bytes32" },
            ],
            name: "updateCampaignStats",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idProm", type: "bytes32" },
            ],
            name: "updatePromStats",
            outputs: [
              { internalType: "bytes32", name: "requestId", type: "bytes32" },
            ],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32", name: "idProm", type: "bytes32" },
            ],
            name: "validateProm",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [
              { internalType: "bytes32[]", name: "idProms", type: "bytes32[]" },
            ],
            name: "validateProms",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [],
            name: "withdraw",
            outputs: [],
            stateMutability: "nonpayable",
            type: "function",
          },
        ],
      },
      oracle: {
        address: {
          mainnet: "",
          testnet: "0x49B1149C975970E47Ad3a16BE3c7701B3f445ECd",
          mainnetBep20: "",
          testnetBep20: "0x11235dca54a882f7a9221fc156b7945de0a4e655",
        },
        abi: [
          {
            anonymous: false,
            inputs: [
              {
                indexed: true,
                internalType: "bytes32",
                name: "idRequest",
                type: "bytes32",
              },
              {
                indexed: false,
                internalType: "uint64",
                name: "likes",
                type: "uint64",
              },
              {
                indexed: false,
                internalType: "uint64",
                name: "shares",
                type: "uint64",
              },
              {
                indexed: false,
                internalType: "uint64",
                name: "views",
                type: "uint64",
              },
            ],
            name: "AnswerRequest",
            type: "event",
          },
          {
            anonymous: false,
            inputs: [
              {
                indexed: true,
                internalType: "bytes32",
                name: "idProm",
                type: "bytes32",
              },
              {
                indexed: false,
                internalType: "uint256",
                name: "nbAbos",
                type: "uint256",
              },
            ],
            name: "AnswerRequestBounty",
            type: "event",
          },
          {
            anonymous: false,
            inputs: [
              {
                indexed: true,
                internalType: "bytes32",
                name: "idRequest",
                type: "bytes32",
              },
              {
                indexed: false,
                internalType: "uint8",
                name: "typeSN",
                type: "uint8",
              },
              {
                indexed: false,
                internalType: "string",
                name: "idPost",
                type: "string",
              },
              {
                indexed: false,
                internalType: "string",
                name: "idUser",
                type: "string",
              },
            ],
            name: "AskRequest",
            type: "event",
          },
          {
            anonymous: false,
            inputs: [
              {
                indexed: false,
                internalType: "uint8",
                name: "typeSN",
                type: "uint8",
              },
              {
                indexed: false,
                internalType: "string",
                name: "idPost",
                type: "string",
              },
              {
                indexed: false,
                internalType: "string",
                name: "idUser",
                type: "string",
              },
              {
                indexed: false,
                internalType: "bytes32",
                name: "idProm",
                type: "bytes32",
              },
            ],
            name: "AskRequestBounty",
            type: "event",
          },
          { payable: true, stateMutability: "payable", type: "fallback" },
          {
            constant: false,
            inputs: [
              {
                internalType: "address",
                name: "campaignContract",
                type: "address",
              },
              { internalType: "bytes32", name: "idRequest", type: "bytes32" },
              { internalType: "uint64", name: "likes", type: "uint64" },
              { internalType: "uint64", name: "shares", type: "uint64" },
              { internalType: "uint64", name: "views", type: "uint64" },
            ],
            name: "answer",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              {
                internalType: "address",
                name: "campaignContract",
                type: "address",
              },
              { internalType: "bytes32", name: "idProm", type: "bytes32" },
              { internalType: "uint256", name: "nbAbos", type: "uint256" },
            ],
            name: "answerBounty",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { internalType: "uint8", name: "typeSN", type: "uint8" },
              { internalType: "string", name: "idPost", type: "string" },
              { internalType: "string", name: "idUser", type: "string" },
              { internalType: "bytes32", name: "idRequest", type: "bytes32" },
            ],
            name: "ask",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { internalType: "uint8", name: "typeSN", type: "uint8" },
              { internalType: "string", name: "idPost", type: "string" },
              { internalType: "string", name: "idUser", type: "string" },
              { internalType: "bytes32", name: "idProm", type: "bytes32" },
            ],
            name: "askBounty",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { internalType: "address", name: "a", type: "address" },
              { internalType: "bool", name: "allow", type: "bool" },
              { internalType: "address", name: "token", type: "address" },
              { internalType: "uint256", name: "fee", type: "uint256" },
            ],
            name: "changeAnswer",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { internalType: "address", name: "a", type: "address" },
              { internalType: "bool", name: "allow", type: "bool" },
            ],
            name: "changeAsk",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: true,
            inputs: [],
            name: "owner",
            outputs: [
              { internalType: "address payable", name: "", type: "address" },
            ],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              {
                internalType: "address",
                name: "campaignContract",
                type: "address",
              },
              { internalType: "bytes32", name: "idRequest", type: "bytes32" },
              { internalType: "uint64", name: "likes", type: "uint64" },
              { internalType: "uint64", name: "shares", type: "uint64" },
              { internalType: "uint64", name: "views", type: "uint64" },
            ],
            name: "thirdPartyAnswer",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              {
                internalType: "address payable",
                name: "newOwner",
                type: "address",
              },
            ],
            name: "transferOwnership",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { internalType: "address", name: "token", type: "address" },
              { internalType: "address", name: "to", type: "address" },
              { internalType: "uint256", name: "val", type: "uint256" },
            ],
            name: "transferToken",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [],
            name: "withdraw",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
        ],
      },
      wSaTT: {
        address: { mainnet: "0x70A6395650b47D94A77dE4cFEDF9629f6922e645" },
        abi: [
          {
            inputs: [
              {
                internalType: "contract IERC223",
                name: "_SATT_addr",
                type: "address",
              },
              {
                internalType: "contract WSATT",
                name: "_WSATT_addr",
                type: "address",
              },
            ],
            payable: false,
            stateMutability: "nonpayable",
            type: "constructor",
          },
          {
            constant: false,
            inputs: [
              { internalType: "uint256", name: "value", type: "uint256" },
            ],
            name: "contributeWSATT",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { internalType: "address", name: "_from", type: "address" },
              { internalType: "uint256", name: "_value", type: "uint256" },
              { internalType: "bytes32", name: "_data", type: "bytes32" },
            ],
            name: "tokenFallback",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
        ],
      },
      priceGap: {
        address: { mainnet: "0xf117674e1890b56be87db3b0dc12750023ee69d9" },
        abi: [
          {
            constant: false,
            inputs: [
              {
                internalType: "address",
                name: "a",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "b",
                type: "uint256",
              },
              {
                internalType: "uint8",
                name: "v",
                type: "uint8",
              },
              {
                internalType: "bytes32",
                name: "r",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "s",
                type: "bytes32",
              },
            ],
            name: "getGap",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              {
                internalType: "address",
                name: "a",
                type: "address",
              },
            ],
            name: "setSatt",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              {
                internalType: "address",
                name: "a",
                type: "address",
              },
            ],
            name: "setSigner",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              {
                internalType: "address payable",
                name: "newOwner",
                type: "address",
              },
            ],
            name: "transferOwnership",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "address",
                name: "to",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "val",
                type: "uint256",
              },
            ],
            name: "transferToken",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            inputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "constructor",
          },
          {
            payable: true,
            stateMutability: "payable",
            type: "fallback",
          },
          {
            constant: false,
            inputs: [],
            name: "withdraw",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: true,
            inputs: [],
            name: "owner",
            outputs: [
              {
                internalType: "address payable",
                name: "",
                type: "address",
              },
            ],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: true,
            inputs: [
              {
                internalType: "address",
                name: "a",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "b",
                type: "uint256",
              },
              {
                internalType: "uint8",
                name: "v",
                type: "uint8",
              },
              {
                internalType: "bytes32",
                name: "r",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "s",
                type: "bytes32",
              },
            ],
            name: "test",
            outputs: [
              {
                internalType: "address",
                name: "",
                type: "address",
              },
            ],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: true,
            inputs: [
              {
                internalType: "address",
                name: "a",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "b",
                type: "uint256",
              },
              {
                internalType: "uint8",
                name: "v",
                type: "uint8",
              },
              {
                internalType: "bytes32",
                name: "r",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "s",
                type: "bytes32",
              },
            ],
            name: "testhash",
            outputs: [
              {
                internalType: "bytes32",
                name: "",
                type: "bytes32",
              },
            ],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: true,
            inputs: [
              {
                internalType: "address",
                name: "_from",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "_value",
                type: "uint256",
              },
              {
                internalType: "bytes",
                name: "_data",
                type: "bytes",
              },
            ],
            name: "tokenFallback",
            outputs: [
              {
                internalType: "bytes32",
                name: "hash",
                type: "bytes32",
              },
            ],
            payable: false,
            stateMutability: "pure",
            type: "function",
          },
        ],
      },

      bep20: {
        address: {
          mainnet: "0x448bee2d93be708b54ee6353a7cc35c4933f1156",
          testnet: "0x6fAc729f346A46fC0093126f237b4A520c40eb89",
          busdMainnet: "0xe9e7cea3dedca5984780bafc599bd69add087d56",
          busdTesnet: "0x4CB4473Af06B844d06b5eDeF08983B2C5C61e5af",
        },
        abi: [
          {
            inputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "constructor",
          },
          {
            anonymous: false,
            inputs: [
              {
                indexed: true,
                internalType: "address",
                name: "owner",
                type: "address",
              },
              {
                indexed: true,
                internalType: "address",
                name: "spender",
                type: "address",
              },
              {
                indexed: false,
                internalType: "uint256",
                name: "value",
                type: "uint256",
              },
            ],
            name: "Approval",
            type: "event",
          },
          {
            anonymous: false,
            inputs: [
              {
                indexed: true,
                internalType: "address",
                name: "previousOwner",
                type: "address",
              },
              {
                indexed: true,
                internalType: "address",
                name: "newOwner",
                type: "address",
              },
            ],
            name: "OwnershipTransferred",
            type: "event",
          },
          {
            anonymous: false,
            inputs: [
              {
                indexed: true,
                internalType: "address",
                name: "from",
                type: "address",
              },
              {
                indexed: true,
                internalType: "address",
                name: "to",
                type: "address",
              },
              {
                indexed: false,
                internalType: "uint256",
                name: "value",
                type: "uint256",
              },
            ],
            name: "Transfer",
            type: "event",
          },
          {
            constant: true,
            inputs: [
              { internalType: "address", name: "owner", type: "address" },
              { internalType: "address", name: "spender", type: "address" },
            ],
            name: "allowance",
            outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { internalType: "address", name: "spender", type: "address" },
              { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            name: "approve",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: true,
            inputs: [
              { internalType: "address", name: "account", type: "address" },
            ],
            name: "balanceOf",
            outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            name: "burn",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: true,
            inputs: [],
            name: "decimals",
            outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { internalType: "address", name: "spender", type: "address" },
              {
                internalType: "uint256",
                name: "subtractedValue",
                type: "uint256",
              },
            ],
            name: "decreaseAllowance",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: true,
            inputs: [],
            name: "getOwner",
            outputs: [{ internalType: "address", name: "", type: "address" }],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { internalType: "address", name: "spender", type: "address" },
              { internalType: "uint256", name: "addedValue", type: "uint256" },
            ],
            name: "increaseAllowance",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            name: "mint",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: true,
            inputs: [],
            name: "name",
            outputs: [{ internalType: "string", name: "", type: "string" }],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: true,
            inputs: [],
            name: "owner",
            outputs: [{ internalType: "address", name: "", type: "address" }],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: false,
            inputs: [],
            name: "renounceOwnership",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: true,
            inputs: [],
            name: "symbol",
            outputs: [{ internalType: "string", name: "", type: "string" }],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: true,
            inputs: [],
            name: "totalSupply",
            outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
            payable: false,
            stateMutability: "view",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { internalType: "address", name: "recipient", type: "address" },
              { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            name: "transfer",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { internalType: "address", name: "sender", type: "address" },
              { internalType: "address", name: "recipient", type: "address" },
              { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            name: "transferFrom",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
          {
            constant: false,
            inputs: [
              { internalType: "address", name: "newOwner", type: "address" },
            ],
            name: "transferOwnership",
            outputs: [],
            payable: false,
            stateMutability: "nonpayable",
            type: "function",
          },
        ],
      },
    };

    app.config.ctrs = Constants;
    resolve(app);
  });
};
